### ISSUE TITLE
Tracking: Player Experience improvements

### ISSUE THREAD

**Issue by vgarleanu** [Dusk-Labs/dim#292]
This issue tracks progress for various player experience improvements.

- [ ] Thumbnail in seekbar support (#250)
- [ ] Chromecast support (#206)
- [ ] MediaSession API support (#126)
- [x] Autoplay next episode (#341)
- [x] Show more details about audio tracks (#260)
- [x] Ability to set default player quality (#254)
- [ ] HDR tonemapping (#246)
- [ ] Add nerd view to player for debuggin (#190)
- [ ] Add route for better log collection during playback crashes (#109)
- [ ] Better subtitles support, including native subtitle rendering (#162)
- [x] Audio transcoding improvements (#161) [PARTIALLY COMPLETE]
- [x] Default to direct play by default (#227)
- [ ] Web player back button (#222)
- [x] Direct play stability improvements (#281)
- [ ] Improve transcoding video quality.
- [ ] Improve video player error reporting.

If I've missed something, feel free to edit this issue and add the item to the list.
