### ISSUE TITLE
Tracking Issue: migrating  from warp to axum

### ISSUE THREAD

**Issue by mental32** [Dusk-Labs/dim#548]
See previous issue #534

The Axum `Router` abstraction is now used at the top-level to route http requests to the appropriate service. The handler services are however still implemented using warp filters (except for the websocket handler)

This is a tracking issue for the remaining endpoints:

- [x] `/api/v1/auth/` `invites::filters::delete_token`
- [x] `/api/v1/auth/` `invites::filters::generate_invite`
- [x] `/api/v1/auth/` `invites::filters::get_all_invites`
- [x] `/api/v1/auth/login` `auth::filters::login`
- [x] `/api/v1/auth/register` `auth::filters::register`
- [x] `/api/v1/auth/whoami` `auth::filters::whoami`
- [x] `/api/v1/dashboard/banner` `dashboard::filters::banners`
- [x] `/api/v1/dashboard` `dashboard::filters::dashboard`
- [x] `/api/v1/episode/` `tv::filters::delete_episode_by_id`
- [x] `/api/v1/episode/` `tv::filters::patch_episode_by_id`
- [x] `/api/v1/filebrowser/*path` `general::filters::get_directory_structure`
- [x] `/api/v1/filebrowser` `general::filters::get_directory_structure`
- [x] `/api/v1/host/admin_exists` `host::filters::admin_exists`
- [x] `/api/v1/host/settings` `settings::filters::get_global_settings`
- [x] `/api/v1/host/settings` `settings::filters::set_global_settings`
- [x] `/api/v1/library/` `library::filters::get_all_of_library`
- [x] `/api/v1/library/` `library::filters::get_all_unmatched_media`
- [x] `/api/v1/library/` `library::filters::library_delete`
- [x] `/api/v1/library/` `library::filters::library_get_self`
- [x] `/api/v1/library/` `library::filters::library_get_self`
- [x] `/api/v1/library/` `library::filters::library_get`
- [x] `/api/v1/library/` `library::filters::library_post`
- [ ] `/api/v1/media/` `media::filters::delete_media_by_id`
- [ ] `/api/v1/media/` `media::filters::get_media_by_id`
- [ ] `/api/v1/media/` `media::filters::get_media_files`
- [ ] `/api/v1/media/` `media::filters::get_mediafile_tree`
- [ ] `/api/v1/media/` `media::filters::map_progress`
- [ ] `/api/v1/media/` `media::filters::tmdb_search`
- [ ] `/api/v1/media/` `media::filters::tmdb_search`
- [ ] `/api/v1/media/` `media::filters::update_media_by_id`
- [ ] `/api/v1/media/` `rematch_media::filters::rematch_media_by_id`
- [ ] `/api/v1/mediafile/` `mediafile::filters::get_mediafile_info`
- [ ] `/api/v1/mediafile/` `mediafile::filters::rematch_mediafile`
- [ ] `/api/v1/search` `general::filters::search`
- [ ] `/api/v1/season/` `tv::filters::delete_episode_by_id`
- [ ] `/api/v1/season/` `tv::filters::delete_season_by_id`
- [ ] `/api/v1/season/` `tv::filters::get_season_episodes`
- [ ] `/api/v1/season/` `tv::filters::patch_episode_by_id`
- [ ] `/api/v1/stream/` `stream::filters::get_chunk`
- [ ] `/api/v1/stream/` `stream::filters::get_init`
- [ ] `/api/v1/stream/` `stream::filters::get_subtitle_ass`
- [ ] `/api/v1/stream/` `stream::filters::get_subtitle_ass`
- [ ] `/api/v1/stream/` `stream::filters::get_subtitle`
- [ ] `/api/v1/stream/` `stream::filters::kill_session`
- [ ] `/api/v1/stream/` `stream::filters::return_manifest`
- [ ] `/api/v1/stream/` `stream::filters::return_virtual_manifest`
- [ ] `/api/v1/stream/` `stream::filters::session_get_stderr`
- [ ] `/api/v1/stream/` `stream::filters::should_client_hard_seek`
- [ ] `/api/v1/tv/` `tv::filters::get_tv_seasons`
- [ ] `/api/v1/user/` `user::filters::change_password`
- [ ] `/api/v1/user/` `user::filters::change_username`
- [ ] `/api/v1/user/` `user::filters::delete`
- [ ] `/api/v1/user/` `user::filters::upload_avatar`
- [ ] `/api/v1/user/settings` `settings::filters::get_global_settings`
- [ ] `/api/v1/user/settings` `settings::filters::get_user_settings`
- [ ] `/api/v1/user/settings` `settings::filters::post_user_settings`
- [ ] `/api/v1/user/settings` `settings::filters::set_global_settings`

The `/` `/static` and `/images` routes are not included in the above list currently.

It is encouraged to open a separate PR for each takeover.

Please edit this description and add your handle at the end of the row for an endpoint to claim it.

**Comment by vgarleanu** [comment]
Warp is no more! Thank you @niamu !
